
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  labels:
    app: laravel
spec:
  selector:
    app: laravel
  type: ClusterIP
  ports:
    - name: http
      port: 80     # Service port
      targetPort: 80 # Container port
 