apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-worker-hpa
  labels:
    app: laravel-app
    role: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-worker
  minReplicas: 1          # At least 1 worker for processing queues
  maxReplicas: 5          # Scale up to 5 workers maximum
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80   # Workers can handle higher CPU usage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85   # Scale when Memory > 85%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100        # Double workers when needed (queue processing)
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300   # Wait longer before scaling down workers
      policies:
      - type: Percent
        value: 25         # Scale down more conservatively
        periodSeconds: 120