apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-worker
  labels:
    app: laravel-app
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
      role: worker
  template:
    metadata:
      labels:
        app: laravel-app
        role: worker
    spec:
      containers:
        - name: worker
          image: laravel-application-local-image-v5:latest
          imagePullPolicy: Never
          workingDir: /var/www  # adjust if your app lives elsewhere
          command:
            - "php"
            - "/var/www/artisan"
            - "queue:work"
            - "--sleep=3"
            - "--tries=3"
            - "--timeout=60"
            - "--queue=default"
          envFrom:
            - secretRef:
                name: laravel-env-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always