
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  labels:
    app: laravel
spec:
  selector:
    app: laravel
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081