apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
data:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "emr"
  DB_USERNAME: "laravel"
  DB_PASSWORD: "laravelpassword"
  SESSION_DRIVER: "file"
  CACHE_STORE: "file"
  QUEUE_CONNECTION: "sync"
  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
