apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-nginx-config
data:
  default.conf: |
    server {
        listen 80;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        
        # Set maximum file upload size to 50MB
        client_max_body_size 50M;

        # Serve storage files directly (user uploads, etc.)
        location /storage/ {
            alias /var/www/storage/app/public/;
            expires 1y;
            add_header Cache-Control "public, immutable";
            try_files $uri =404;
        }

        # Send ALL other requests to PHP-FPM (including static files like CSS/JS)
        location / {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
            fastcgi_param SCRIPT_NAME /index.php;
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param DOCUMENT_ROOT /var/www/public;
            
            # Increase timeouts for large requests
            fastcgi_read_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_connect_timeout 60;
            
            # Buffer settings
            fastcgi_buffering on;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 4 256k;
            fastcgi_busy_buffers_size 256k;
        }
    }
